import React from 'react';

const WordFetcher = () => {
  const words = [

    // Frukt
    { spanish: 'aguacate', swedish: 'avokado' },
    { spanish: 'platano', swedish: 'matbanan' },
    { spanish: 'banana', swedish: 'banan' },
    { spanish: 'ciruela', swedish: 'plommon' },
    { spanish: 'cereza', swedish: 'körsbär' },
    { spanish: 'chocolate', swedish: 'choklad' },
    { spanish: 'fresa', swedish: 'jordgubbe' },
    { spanish: 'granada', swedish: 'granatäpple' },
    { spanish: 'kiwi', swedish: 'kiwi' },
    { spanish: 'limon', swedish: 'citron' },
    { spanish: 'manzana', swedish: 'äpple' },
    { spanish: 'melocoton', swedish: 'persika' },
    { spanish: 'melon', swedish: 'melon' },
    { spanish: 'naranja', swedish: 'apelsin' },
    { spanish: 'pera', swedish: 'päron' },
    { spanish: 'piña', swedish: 'ananas' },
    { spanish: 'sandia', swedish: 'vattenmelon' },
    { spanish: 'uvas', swedish: 'vindruvor' },
    { spanish: 'papa', swedish: 'potatis' },
    { spanish: 'pimiento', swedish: 'paprika' },
    { spanish: 'pepino', swedish: 'gurka' },
    { spanish: 'lechuga', swedish: 'isbergssallad' },
    { spanish: 'tomate', swedish: 'tomat' },
    { spanish: 'cebolla', swedish: 'lök' },
    { spanish: 'ajo', swedish: 'vitlök' },
    { spanish: 'espinaca', swedish: 'spenat' },
    { spanish: 'remolacha', swedish: 'rödbetor' },
    
    // vardagsord
    { spanish: 'adios', swedish: 'adjö' },
    { spanish: 'llave', swedish: 'nyckel' },
    { spanish: 'puerta', swedish: 'dörr' },
    { spanish: 'cerveza', swedish: 'öl' },
    { spanish: 'vino', swedish: 'vin' },
    { spanish: 'hola', swedish: 'hej' },
    { spanish: 'reloj', swedish: 'armbandsur' },
    { spanish: 'bienvenidos', swedish: 'välkommen' },
    { spanish: 'ahora', swedish: 'nu' },
    { spanish: 'hora', swedish: 'tid/timma' },
    { spanish: 'amigos', swedish: 'vänner' },
    { spanish: 'cama', swedish: 'säng' },
    { spanish: 'cancion', swedish: 'sång' },
    { spanish: 'cena', swedish: 'middag' },
    { spanish: 'dia', swedish: 'dag' },
    { spanish: 'desayuno', swedish: 'frukost' },
    { spanish: 'hombre', swedish: 'man' },
    { spanish: 'hoy', swedish: 'idag' },
    { spanish: 'libro', swedish: 'bok' },
    { spanish: 'madre', swedish: 'moder' },
    { spanish: 'manos', swedish: 'händer' },
    { spanish: 'mesa', swedish: 'bord' },
    { spanish: 'noche', swedish: 'kväll' },
    { spanish: 'novia', swedish: 'flickvän' },
    { spanish: 'novio', swedish: 'pojkvän' },
    { spanish: 'ordenador', swedish: 'dator' },
    { spanish: 'padre', swedish: 'fader' },
    { spanish: 'pelo', swedish: 'hår' },
    { spanish: 'trabajo', swedish: 'arbete' },
    { spanish: 'ventana', swedish: 'fönster' },
    { spanish: 'silla', swedish: 'stol' },
    
    // Djur
    { spanish: 'cucaracha', swedish: 'kackerlacka' },
    { spanish: 'caracol', swedish: 'snigel' },
    { spanish: 'lagartija', swedish: 'ödla' },
    { spanish: 'rana', swedish: 'groda' },
    { spanish: 'mariposa', swedish: 'fjäril' },
    { spanish: 'pajaro', swedish: 'fågel' },
    { spanish: 'alce', swedish: 'älg' },
    { spanish: 'araña', swedish: 'spindel' },
    { spanish: 'ardilla', swedish: 'ekorre' },
    { spanish: 'caballo', swedish: 'häst' },
    { spanish: 'cerdo', swedish: 'gris' },
    { spanish: 'chinchilla', swedish: 'chinchilla' },
    { spanish: 'elefante', swedish: 'elefant' },
    { spanish: 'erizo', swedish: 'igelkott' },
    { spanish: 'gato', swedish: 'katt' },
    { spanish: 'leon', swedish: 'lejon' },
    { spanish: 'lince', swedish: 'lodjur' },
    { spanish: 'mono', swedish: 'apa' },
    { spanish: 'perro', swedish: 'hund' },
    { spanish: 'pez', swedish: 'fisk' },
    { spanish: 'raton', swedish: 'mus' },
    { spanish: 'tigre', swedish: 'tiger' },
    { spanish: 'rata', swedish: 'råtta' },
    { spanish: 'vaca', swedish: 'ko' },
    { spanish: 'zorro', swedish: 'räv' },

    // Kläder
    { spanish: 'abrigo', swedish: 'kappa' },
    { spanish: 'bufanda', swedish: 'sjal' },
    { spanish: 'camisa', swedish: 'skjorta' },
    { spanish: 'camiseta', swedish: 't-shirt' },
    { spanish: 'chaqueta', swedish: 'jacka' },
    { spanish: 'corbata', swedish: 'slips' },
    { spanish: 'falda', swedish: 'kjol' },
    { spanish: 'gorro', swedish: 'mössa' },
    { spanish: 'pantalones', swedish: 'byxor' },
    { spanish: 'zapatos', swedish: 'skor' },
    { spanish: 'botas', swedish: 'stövlar' },

    // Grundfärger
    { spanish: 'amarillo', swedish: 'gul' },
    { spanish: 'azul', swedish: 'blå' },
    { spanish: 'beige', swedish: 'beige' },
    { spanish: 'gris', swedish: 'grå' },
    { spanish: 'marron', swedish: 'brun' },
    { spanish: 'morado', swedish: 'lila' },
    { spanish: 'negro', swedish: 'svart' },
    { spanish: 'rojo', swedish: 'röd' },
    { spanish: 'turquesa', swedish: 'turkos' },
    { spanish: 'verde', swedish: 'grön' },
    { spanish: 'naranja', swedish: 'orange' },
    { spanish: 'rosa', swedish: 'rosa' },
    { spanish: 'bronce', swedish: 'brons' },
    { spanish: 'oro', swedish: 'guld' },
    { spanish: 'plata', swedish: 'silver' },

    // Resor
    { spanish: 'avion', swedish: 'flygplan' },
    { spanish: 'autobus', swedish: 'buss' },
    { spanish: 'billete', swedish: 'biljett' },
    { spanish: 'coche', swedish: 'bil' },
    { spanish: 'guia', swedish: 'guide' },
    { spanish: 'hotel', swedish: 'hotell' },
    { spanish: 'maleta', swedish: 'resväska' },
    { spanish: 'mapa', swedish: 'karta' },
    { spanish: 'pasaporte', swedish: 'pass' },
    { spanish: 'taxi', swedish: 'taxi' },
    { spanish: 'tren', swedish: 'tåg' },
    { spanish: 'mochila', swedish: 'ryggsäck' },

    // Övriga ord
    { spanish: 'bosque', swedish: 'skog' },
    { spanish: 'higo', swedish: 'fikon' },
    { spanish: 'coliflor', swedish: 'blomkål' },
    { spanish: 'brocoli', swedish: 'broccoli' },
    { spanish: 'papaya', swedish: 'papaya' },
    { spanish: 'pais', swedish: 'land' },
    { spanish: 'rio', swedish: 'flod' },
    { spanish: 'mujer', swedish: 'kvinna' },
    { spanish: 'niña', swedish: 'tös' },
    { spanish: 'niño', swedish: 'grabb' },
    { spanish: 'chica', swedish: 'flicka' },
    { spanish: 'chico', swedish: 'pojke' },
    { spanish: 'ayer', swedish: 'igår' },
    { spanish: 'uno', swedish: 'ett' },
    { spanish: 'dos', swedish: 'två' },
    { spanish: 'tres', swedish: 'tre' },
    { spanish: 'cuatro', swedish: 'fyra' },
    { spanish: 'cinco', swedish: 'fem' },
    { spanish: 'seis', swedish: 'sex' },
    { spanish: 'siete', swedish: 'sju' },
    { spanish: 'ocho', swedish: 'åtta' },
    { spanish: 'nueve', swedish: 'nio' },
    { spanish: 'diez', swedish: 'tio' },
    { spanish: 'huevo', swedish: 'ägg' },
    { spanish: 'estrella', swedish: 'stjärna' },
    { spanish: 'boca', swedish: 'mun' },
    { spanish: 'dedos', swedish: 'fingrar' },
    { spanish: 'lampara', swedish: 'lampa' },
    { spanish: 'harina', swedish: 'mjöl' },
    { spanish: 'año', swedish: 'år' },
    { spanish: 'baño', swedish: 'badrum' },
    { spanish: 'aseo', swedish: 'toalett' },
    { spanish: 'casa', swedish: 'hem/hus' },
    { spanish: 'dueño', swedish: 'ägare' },
    { spanish: 'mañana', swedish: 'morgon' },
    { spanish: 'montaña', swedish: 'berg' },
    { spanish: 'nuevo', swedish: 'ny' },
    { spanish: 'pequeño', swedish: 'liten' },
    { spanish: 'señal', swedish: 'signal' },
    { spanish: 'señor', swedish: 'herr' },
    { spanish: 'señora', swedish: 'fru/dam' },
    { spanish: 'sueño', swedish: 'dröm' },

    //Överkurs ;)
    { spanish: 'frijoles', swedish: 'bönor' },
    { spanish: 'aguila', swedish: 'örn' },
    { spanish: 'movil', swedish: 'mobil' },
    { spanish: 'familia', swedish: 'familj' },
    { spanish: 'gallina', swedish: 'höna' },
    { spanish: 'pollo', swedish: 'kyckling' },
    { spanish: 'pato', swedish: 'anka' },
    { spanish: 'poto', swedish: 'rumpa' },
    { spanish: 'hermano', swedish: 'broder' },
    { spanish: 'hermana', swedish: 'syster' },
    { spanish: 'fruta', swedish: 'frukt' },
    { spanish: 'jarabe', swedish: 'sirap' },
    { spanish: 'verdura', swedish: 'grönsak' },
    { spanish: 'cacahuete', swedish: 'jordnöt' },
    { spanish: 'arroz', swedish: 'ris' },
    { spanish: 'especias', swedish: 'kryddor' },
    { spanish: 'lentejas', swedish: 'matlinser' },
    { spanish: 'helado', swedish: 'glass' },
    { spanish: 'salsa', swedish: 'sås' },
    { spanish: 'garbanzos', swedish: 'kikärtor' },
    { spanish: 'sal', swedish: 'salt' },
    { spanish: 'pimienta', swedish: 'peppar' },
    { spanish: 'nueces', swedish: 'nötter' },
    { spanish: 'nuez', swedish: 'nöt' },
    { spanish: 'almendra', swedish: 'mandel' },
    { spanish: 'pistachos', swedish: 'pistagenötter' },
    { spanish: 'canela', swedish: 'kanel' },
    { spanish: 'cardamomo', swedish: 'kardemumma' },
    { spanish: 'comino', swedish: 'spiskummin' },
    { spanish: 'pimentón', swedish: 'paprikapulver' },
    { spanish: 'oregano', swedish: 'oregano' },
    { spanish: 'albahaca', swedish: 'basilika' },
    { spanish: 'azucar', swedish: 'socker' },
    { spanish: 'gallo', swedish: 'tupp' },
    { spanish: 'primo', swedish: 'kusin' },
    { spanish: 'ojo', swedish: 'öga' },
    { spanish: 'labios', swedish: 'läppar' }
  ];
  return words;
};

export default WordFetcher;